<?php
/**
 * PHPUnit bootstrap for the event-manager plugin.
 *
 * Relies on Composer's autoloader generated by `composer install` inside this
 * plugin directory (dev-only tooling: phpunit + symfony/yaml). PSR-4 maps:
 *   - Grav\Plugin\EventManager\        -> src/
 *   - Grav\Plugin\EventManager\Tests\  -> tests/
 */

declare(strict_types=1);

$autoload = __DIR__ . '/../vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(
        STDERR,
        "Composer autoloader not found. Run `composer install` inside "
        . "config/www/user/plugins/event-manager/ before running the tests.\n"
    );
    exit(1);
}
require $autoload;
