<?php
/**
 * PHPUnit bootstrap for the feature-flags plugin.
 *
 * We rely on Composer's autoloader generated by `composer install` inside
 * this plugin directory. PSR-4 maps are configured in composer.json:
 *   - Grav\Plugin\FeatureFlags\       -> src/
 *   - Grav\Plugin\FeatureFlags\Tests\ -> tests/
 */

declare(strict_types=1);

$autoload = __DIR__ . '/../vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(
        STDERR,
        "Composer autoloader not found. Run `composer install` inside "
        . "config/www/user/plugins/feature-flags/ before running the tests.\n"
    );
    exit(1);
}
require $autoload;
